---
name: AirCast 2
version: dev
slug: aircast2
description: AirPlay 2 capabilities for your Chromecast devices.
url: https://github.com/BRid37/app-aircast
startup: services
init: false
arch:
  - aarch64
  - amd64
hassio_api: true
host_network: true
map:
  - addon_config:rw
options:
  mode: easy
  latency_offset: 0
  airplay_mode: classic
schema:
  log_level: list(trace|debug|info|warning|error)?
  mode: list(easy|advanced)
  whole_house_group: str?
  latency_offset: int
  airplay_mode: list(classic|airplay2)
  excluded_devices:
    - str
